### ISSUE TITLE
A Smart Unique Question

### ISSUE THREAD

**Issue by theomgdev** [thiagodp/database-js-json#1]
How to insert? An example?

**Comment by thiagodp** [comment]
Hello @M4YX0R, you can insert a row like this:

```js
const st = conn.prepareStatement( 'INSERT VALUES { "name": "Mary", "age": 18 }' );
await st.execute();
```

**Comment by thiagodp** [comment]
Examples for INSERT, UPDATE, and DELETE were added to the documentation (README.md). 👍
